// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlvqoevnmhmgowcchxfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsdnFvZXZubWhtZ293Y2NoeGZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTQ0NzgsImV4cCI6MjA3MzUzMDQ3OH0.Dx_uDVDcJXvcOfjWj9oze7orCt8iU6r6OD5Ut1ZoW2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});